
echo "Henlo little one, AKA. Aadhithyashri M S, Happy birthday... Have a nice year"
echo "Here are cool facts about 14th NOV"
echo "318th day of the Gregoriann calendar but who tf asked idk"
echo "Also National pickle day (i think in te US) which means more pickled for your subs"
echo "World Diabeted day... Celebrate the lack of insulin"
echo "International Girls' day... not for you but sure"
echo "Children's Day for smol little Aadhi"
echo "And AADHI DAY!!!!!!!!! aadhiday>>>>svesday "
echo "I forgot shell scripting but i think this will work"
echo "here's the last flag : flag{fR0m!V}"